package com.yumenonaka.ymnkapp.screens.sound_effect

import com.yumenonaka.ymnkapp.models.app.SoundEffect

val soundEffects = listOf(
    SoundEffect("ユメ入り", "yumeiri.mp3"),
    SoundEffect("ユメ入りいい", "yumeiriii.mp3"),
    SoundEffect("おやすみなー", "oyasumina.mp3"),
    SoundEffect("バーーーン", "ban.mp3"),
    SoundEffect("晚安", "wanan.mp3"),
    SoundEffect("晚安～～", "wanaaan.mp3"),
    SoundEffect("あんあん～", "angang.mp3"),
    SoundEffect("わんわん～", "wanwang.mp3"),
    SoundEffect("ユメノシオリだよ！", "yumenoshioridayo.mp3"),
    SoundEffect("ユメ堕つー", "yumeotsu_long.mp3"),
    SoundEffect("ユメ堕つっ", "yumeotsu_short.mp3"),
    SoundEffect("おやすみなーさい", "oyasuminasai_long.mp3"),
    SoundEffect("おやすみなさい", "oyasuminasai_short.mp3"),
    SoundEffect("おっと～", "otto.mp3"),
    SoundEffect("おにいーちゃん", "oniichan_long.mp3"),
    SoundEffect("おにいちゃん", "oniichan_short.mp3"),
    SoundEffect("連打！", "renda.mp3"),
    SoundEffect("フルコンボだドン", "furukonnbodadon.mp3"),
    SoundEffect("Great!", "shiori_great.mp3"),
    SoundEffect("Excellent!", "shiori_excellent.mp3"),
    SoundEffect("Excellent! 2", "shiori_excellent2.mp3"),
    SoundEffect("Shiori punch", "shiori_punch.mp3"),
    SoundEffect("Shiori punch 2", "shiori_punch2.mp3"),
    SoundEffect("えい！えい！えい！", "eieiei.mp3"),
    SoundEffect("あんあんーー", "anaaan.mp3"),
    SoundEffect("ひゃぁぁぁ", "hyaaa.mp3"),
    SoundEffect("忘れろビーム！", "wasurero_beam.mp3"),
    SoundEffect("ねっ", "shiori_ne.mp3"),
    SoundEffect("おっぱいいいい", "oppai.mp3"),
    SoundEffect("ごめんなさい", "gomennnasai1.mp3"),
)
