package com.yumenonaka.ymnkapp.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF942CB0)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFDD6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF340042)
val md_theme_light_secondary = Color(0xFF6A596C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF3DBF2)
val md_theme_light_onSecondaryContainer = Color(0xFF241727)
val md_theme_light_tertiary = Color(0xFF82524C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD6)
val md_theme_light_onTertiaryContainer = Color(0xFF33110E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1A1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1A1E)
val md_theme_light_surfaceVariant = Color(0xFFECDFE9)
val md_theme_light_onSurfaceVariant = Color(0xFF4C444C)
val md_theme_light_outline = Color(0xFF7E747D)
val md_theme_light_inverseOnSurface = Color(0xFFF7EEF3)
val md_theme_light_inverseSurface = Color(0xFF332F33)
val md_theme_light_inversePrimary = Color(0xFFF3AEFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF942CB0)

val md_theme_dark_primary = Color(0xFFF3AEFF)
val md_theme_dark_onPrimary = Color(0xFF55006A)
val md_theme_dark_primaryContainer = Color(0xFF790096)
val md_theme_dark_onPrimaryContainer = Color(0xFFFDD6FF)
val md_theme_dark_secondary = Color(0xFFD6C0D6)
val md_theme_dark_onSecondary = Color(0xFF3A2B3C)
val md_theme_dark_secondaryContainer = Color(0xFF524153)
val md_theme_dark_onSecondaryContainer = Color(0xFFF3DBF2)
val md_theme_dark_tertiary = Color(0xFFF5B7B0)
val md_theme_dark_onTertiary = Color(0xFF4C2521)
val md_theme_dark_tertiaryContainer = Color(0xFF673B36)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1A1E)
val md_theme_dark_onBackground = Color(0xFFE8E0E5)
val md_theme_dark_surface = Color(0xFF1E1A1E)
val md_theme_dark_onSurface = Color(0xFFE8E0E5)
val md_theme_dark_surfaceVariant = Color(0xFF4C444C)
val md_theme_dark_onSurfaceVariant = Color(0xFFCFC3CD)
val md_theme_dark_outline = Color(0xFF988E97)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1A1E)
val md_theme_dark_inverseSurface = Color(0xFFE8E0E5)
val md_theme_dark_inversePrimary = Color(0xFF942CB0)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFF3AEFF)


val seed = Color(0xFF8E24AA)
